application: data-gearbox-368
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on
- deferred: on
- remote_api: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /favicon.ico 
  static_files: static/favicon.ico 
  upload: static/favicon.ico 
  mime_type: image/x-icon 

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin
- url: /.*
  script: yx.application
